name: PR Validation

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  pr-validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: "16.15.x"

      - name: NPM install, NPM install next
        run: |
          npm install 
          npm install next

      - name: Run unit tests
        run: npm run test

      - name: Run ESLint
        run: npm run lint:all

      - name: Run type check
        run: npm run typecheck

      - name: build
        run: npm run build
